---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secret.djangoSecretKey | b64enc | quote }}