---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-devops-python-data
  namespace: demo-devops
  labels:
    app: demo-devops-python
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
